<?php
/**
 * Base TestCase for Integration Tests (wp-phpunit)
 *
 * Extends the WordPress WP_UnitTestCase which provides:
 *   - A real MySQL database (transaction-wrapped, rolled back after each test)
 *   - All WordPress functions available (get_post_meta, wp_insert_post, etc.)
 *   - Factory helpers for creating posts, users, terms, etc.
 *
 * Use this for anything that touches the database: Task_Runner metadata,
 * Action Scheduler interactions, REST endpoints, post-meta-based test
 * fixtures. v2 (2026-05-01) retired Campaign_Repository — campaigns
 * live on cloud Firestore now, so tests that previously round-tripped
 * `_cluster_*` post meta are obsolete.
 */

namespace Structura\Tests\Integration;

use WP_UnitTestCase;

abstract class TestCase extends WP_UnitTestCase
{
    /**
     * Create a minimal `structura_campaign` post and return its ID.
     *
     * Used by tests that need a real campaign post id to attach
     * meta to (Run_Signal_Service / Channel_Event_Forwarder gating
     * tests, Builder_Compat opt-out tests, etc.). v2 retired the
     * `_cluster_*` post-meta layer; campaigns themselves live on
     * cloud Firestore now, so this helper just creates a stub post
     * for tests that still need a WP post id pointer.
     */
    protected function create_campaign_post(string $title = 'Test Campaign'): int
    {
        $id = wp_insert_post([
            'post_title'  => $title,
            'post_type'   => 'structura_campaign',
            'post_status' => 'publish',
        ]);

        $this->assertIsInt($id);
        $this->assertGreaterThan(0, $id);

        return $id;
    }

    /**
     * Returns a complete, valid campaign data array suitable for
     * Campaign_Validator::validate() (the only consumer left after v2
     * retired Campaign_Repository::update_meta).
     *
     * Override individual keys in tests to create specific scenarios.
     */
    protected function get_default_campaign_data(array $overrides = []): array
    {
        return array_merge([
            'name'                   => 'Test Campaign',
            'topic'                  => 'A sufficiently long topic about AI content generation strategies',
            'campaign_mode'          => 'traffic_magnet',
            // Explicit text/image providers on every payload. `provider`
            // stays in the fixture as the legacy alias the React client
            // still sends for back-compat.
            'provider'               => 'gemini',
            'text_provider'          => 'gemini',
            'image_provider'         => 'gemini',
            'text_model'             => 'gemini-pro',
            'image_model'            => 'imagen-3',
            'persona_id'             => 1,
            'language'               => 'en',
            'post_length'            => 1200,
            'replace_long_dashes'    => false,
            'disable_emojis'         => false,
            'seo_optimization_rules' => ['use_keyphrase' => true],
            'enabled_blocks'         => ['core/paragraph', 'core/heading', 'core/list'],
            'featured_image'         => true,
            'body_images'            => false,
            'enable_disclosure'      => true,
            'disclosure_text'        => 'This post was generated by AI.',
            'category_mode'          => 'auto',
            'allowed_categories'     => [],
            'tag_mode'               => 'auto',
            'allowed_tags'           => [],
            'cron_schedule'          => '0 9 * * 1',
            'end_mode'               => 'quota',
            'end_posts'              => 10,
            'end_date'               => '',
        ], $overrides);
    }
}
